import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "10dd69a5f17f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "encrypted_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.LargeBinary(), nullable=False),
        sa.Column("secret_key", sa.String(length=128), nullable=False),
        sa.Column("is_removed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_encrypted_message_secret_key"),
        "encrypted_message",
        ["secret_key"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_encrypted_message_secret_key"), table_name="encrypted_message"
    )
    op.drop_table("encrypted_message")
    # ### end Alembic commands ###
